### PR TITLE
Footer support

### PR DESCRIPTION
**Pull request by evil159**
## Details

This PR adds footer support to MagazineLayout.

## Related Issue

#18 

## Motivation and Context

Footers are quite common when dealing with collection view sections. 

## How Has This Been Tested

Tested using the example project and unit tests. 

## Types of changes

- [ ] Docs change / refactoring / dependency upgrade
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [x] I have added tests to cover my changes.

### CODE REVIEW

**Comment by bryankeller** [comment]
@evil159 thanks so much for taking on this work! I've been a bit busy, but will be able to look at this next week. Thank you for your patience 🙂

**Comment by diegorozen** [comment]
@bryankeller Is there anything blocking this PR. It would be a great addition to the library. Thanks again!

**Comment by bryankeller** [comment]
Closing in favor of https://github.com/airbnb/MagazineLayout/pull/31. Please take a look @evil159

**Comment by bryankeller** [comment]
Closing in favor of #31 - please take a look @evil159

**Pull request closed without merging**
