### PR TITLE
Update for Swift 5 and Xcode 13.2

### PR DESCRIPTION
**Pull request by jordanekay**
Updates the codebase for Swift 5 ~and fixes warnings on Xcode 13.2~.

Edit by @bryankeller: Removed the warning fixes for dangling pointers. I'll fix this in a separate PR.

### CODE REVIEW

**Comment by jeanetienne** [comment]
Super keen to get this one merged, how can I help?

**Comment by bryankeller** [comment]
Sorry for the delay! I'll take a look at this in the next few days and we can get this merged. Thanks for your patience!

**Comment by jeanetienne** [comment]
> Sorry for the delay! I'll take a look at this in the next few days and we can get this merged. Thanks for your patience!

No problem at all! Thank you for open sourcing this component, and let me know if I can help?

/cc @kimrypstraHE

**Review by bryankeller — APPROVED** [review]
Thanks for doing the migration! I removed the dangling pointer warning fixes from this and did them separately in this PR https://github.com/airbnb/MagazineLayout/pull/106

**Pull request merged**
